@endpoint = https://cnnmihhs5a.execute-api.us-west-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Canada",
    "name": "Toronto",
    "score": 10
}
###